### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [troglobit/editline#14]
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream") ⇒ [write_history](https://github.com/troglobit/editline/blob/059d97d7a939019ccafe901c82a6d2d474dca62f/src/editline.c#L1274)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string") ⇒ [search_hist](https://github.com/troglobit/editline/blob/2a3575495ad779185459a3294ad857ea7208c899/src/editline.c#L593)

**Comment by troglobit** [comment]
The former yes, the latter no, not needed.

Fixed in ea79fe7.

**Comment by elfring** [comment]
>…, the latter no, not needed.

Why? - I find this view questionable.

I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to [detect every error situation as early as possible](https://github.com/troglobit/editline/commit/ea79fe70f9c9ff725bbb69e1974640f72ec74899#diff-532aa92b0f7db9561ed48bb41ec87506L1357 "Update candidate: write_history()")?

**Comment by troglobit** [comment]
The latter is checked the next time the function is called.

**Comment by elfring** [comment]
I find the current error detection and corresponding exception handling still incomplete.
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for your software?

**Comment by troglobit** [comment]
Well, that's your opinion, which you're entitled to. From my point of view this is becoming a bit tiresome, your constant nitpicking on every tiny aspect and never submitting any pull requests or patches of your own.  I appreciate bug reports, but you have to also know when to stop requesting favors for free, and try to get a feel for when you're taking things a bit too far. As a maintainer it is not my job to fulfill the requests of everyone filing an issue. If you're a user of editline, then grab a shovel and help out, or fork the project if you're dissatisfied with my maintainership. Thank you.

Coverity Scan is already active for this project, a run will be scheduled before the next upcoming release.

**Comment by elfring** [comment]
>…, your constant nitpicking on every tiny aspect

I dare to point further improvement possibilities out.


>and never submitting any pull requests or patches of your own.

This view can be appropriate for your software so far. But the situation is different if you look at my contributions in other information systems.


>As a maintainer it is not my job to fulfill the requests of everyone filing an issue.

This view is generally appropriate. - There are more options available to change the affected software.


>Coverity Scan is already active for this project, …

I am curious if [this analysis tool](https://scan.coverity.com/projects/troglobit-editline/ "Source code analysis by Coverity") will point similar open issues out which I mentioned here.

**Comment by troglobit** [comment]
Dude, do you really have to have the last word in everything?  I stopped even considering doing more work in the pingfs project because you literally took the fun out of it!

In this particular case, pertaining to this issue, you say " I find this view questionable.", which means you question my judgment. So, let's have a look at that `strdup()` that's in contention here:

- it's for saving the i-search string, so that a subsequent search *may* reuse it
- the function itself search the history, returning a match or not

Would one want `search_hist()` to fail for not managing to (conveniently) save the string I just search for?  In my opinion, no.  The responsibility of the function is to search the history to return any match of a prior `readline()` entry. If this function is called again it will have no knowledge of any prior search, due to the `strdup()` having failed. Which, again in my view, is OK since there are no side effects apart from loss of the last search term.

The whole point of the library is to make it easy to read a line, not to barf on every possible error, and that's the design philosophy I am likely maintain for the duration. You may have another approach to things, and that's fine, but in this project I'm the sole maintainer and don't have to explain every single decision. 

I encourage your "more options", like forking, patching or whatnot, let a thousand flowers bloom, as they say. Had we not got off on the wrong foot I might have given you access to my Coverity Scan results.

**Comment by rofl0r** [comment]
it seems it's not very hard [to get off on the wrong foot with you](https://github.com/troglobit/redir/issues/2#issuecomment-324396021) . would you consider being more friendly to your users ? 😁

**Comment by troglobit** [comment]
@rofl0r So far, in my "career" on GitHub I've had disagreements on design and error handling with two people, and fruitful collaborations with several others. I'm not sure that could be characterized as being unfriendly, but that is for others to decide, I'm not that vain.

What is interesting to note, though, is that a difference of opinion and decision by a maintainer can be so hard to accept for some as the end of a discussion.
