### ISSUE TITLE
Feature request: able to gracefully end readline() from another thread

### ISSUE THREAD

**Issue by abitmore** [troglobit/editline#27]
When `readline()` is running in a thread waiting for input from tty, terminal is prepped, the function blocks until got an "end" (e.g. EOL, EOF, SIGINT or etc) from tty. In case when another thread decided to no longer accept input from tty (e.g. timeout or got a signal from outside), we need a way to gracefully end `readline()` and restore terminal, rather than waiting for an end. We can't forcefully end the thread because terminal won't be restored.

**Comment by troglobit** [comment]
We have the new alternate interface, for event loops, https://github.com/troglobit/editline/commit/bc7fc7e, which may be of interest to you.

There is also the option of using a different `rl_getc_function`.  Editline defaults to use the local `rl_getc()` fucntion which uses `read()`, which is wrapped in a do-while(EINTR)-loop to handle aborted syscalls due to signals.  So if you like you could do another implementation of that and install a signal handler in the thread (to prevent the thread from dying), upon return from `readline()` the TTY will be restored by `el_deprep()`.

Maybe GNU Readline has some other API or method for this, but at this point I haven't looked into that.

**Comment by abitmore** [comment]
Thanks. I'll take a look. I was trying to modify `rl_getc()` just now.

**Comment by troglobit** [comment]
I added a reference implementation for the alternate API in `examples/excallback.c`.  Having everything in the same thread/process is sometimes the preferred way to go.  In particular if you use libev or some other neat event loop instead of rolling your own (as the example does).

**Comment by abitmore** [comment]
If I'm correct, current implementation of `rl_getc()` ignores SIGINT directly, thus I need a new implementation anyway, even if I go for the alternate API approach. Created PR #29 for this.

The links you provided in #28 is useful for this discussion:
* Signals handling: http://www.delorie.com/gnu/docs/readline/rlman_43.html
* Example of alternate API: https://stackoverflow.com/a/27662212

**Comment by troglobit** [comment]
You're almost correct.  The `rl_getc()` implementation ignores *any* signal by checking for `EINTR` and restarting the syscall.  This is common practice in UNIX.

**Comment by abitmore** [comment]
FWIW, [my implementation of `rl_getc()`](https://github.com/bitshares/bitshares-fc/blob/51747090a836611ac2067f2174f566fc8b650a22/src/rpc/cli.cpp#L260-L271) looks like:
```
static int interruptible_getc(void)
{
   int r;
   char c;

   r = read(0, &c, 1); // read from stdin, will return -1 on SIGINT

   return r == 1 ? c : EOF;
}
```
seems work for me.

**Comment by troglobit** [comment]
Yup, that definitely looks like it should work for you.  You may want to keep a list of which signals your application handles and add a check in `interruptible_getc()` to make sure you only return EOF when there is SIGINT and not another signal ...

... so maybe we can close this issue now?

**Comment by abitmore** [comment]
Thanks. Closing. BTW I've updated the sample code above to handle interruption during searching.
