### ISSUE TITLE
Run with mpi

### ISSUE THREAD

**Issue by tuanhtrng** [troglobit/editline#43]
I use editline with mpi and have the loop in rank 0. Everything seems OK except the prompt message.

**Comment by troglobit** [comment]
Hi, I don't know what an "mpi" or "rank" is.  How to set the prompt, however, is documented in many places in this project; the [manual page](https://man.troglobit.com/man3/editline.3.html) and the [README](https://github.com/troglobit/editline#example).

However, I'm guessing you're not even using this version of the editline library. But it's really difficult to answer since you've provided little to no information for me to help you: what version of editline are you using, what did you try to do, can you provide an example snippet of code that breaks for you?

**Comment by tuanhtrng** [comment]
Hello, apologize for my cryptic message. Check this [pastebin ](https://pastebin.com/3z8wd4d8) for the code.

When I ran the binary stand-alone or with `mpirun -np 1`, everything works as intended. At higher -np value, the program just a simple stdin.

**Comment by troglobit** [comment]
Like I said, I don't know what MPI is, giving me an URL for a pastebin of your code doesn't help if I don't know what the context is.  Googling, it seems to be some framework for message passing in parallel programming?  If that means threading it could explain your problems.  The old editline library was made for single threaded applications, and it has many global variables that make it quite thread unsafe.

**Comment by troglobit** [comment]
No response for almost a year, closing.
